### ISSUE TITLE
error","plugins","wazuh","cron-scheduler"],"pid":55,"message":"Error: connect ECONNREFUSED 10.43.211.123:55000

### ISSUE THREAD

**Issue by Tuurkevg** [morgoved/wazuh-helm#11]
Hey, I'm having some problems with setting up your Helm chart. I use Flux to deploy everything, so here are just the values. With the current setup, Kibana server cannot reach the API server, and it keeps saying that it is offline. From inside the cluster, I tried testing with a random container to see if I could reach port 55000, but that failed.

If someone could help me find the problem, that would be helpfull!
```

my helmrease yaml
  values:
    cert-manager:
      enabled: false
    imagePullSecrets: []
    # Kibana for elasticsearch with Wazuh plugins pre-installed
    dashboard:      
      replicas: 2
      annotations: {}
      podAnnotations: {}

      images:
        repository: wazuh/wazuh-dashboard
        tag: "4.11.1"
        pullPolicy: IfNotPresent
      
      resources:
        limits:
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 512Mi
      
      pdb:
        enabled: false
        maxUnavailable: 1

      networkPolicy:
        enabled: false
      enable_ssl: true

      service:
        annotations: {}
        httpPort: 5601
        type: ClusterIP
      
      cred:
        existingSecret: ""
        username: "kibanaserver"
        password: "kibanaserver"
      
      config: |
        {{- include "wazuh.dashboard.config" . | indent 2 -}}
      
      ingress:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"  # Set backend protocol to HTTPS        
          cert-manager.io/cluster-issuer: ca-certsrv        
        hosts:
          - host: wazuh-dashboard.it.excentis.com
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: wazuh-dashboard-ingress-tls
            hosts:
              - wazuh-dashboard.it.excentis.com
        
    indexer:
      replicas: 3
      service:
        annotations: {}
        httpPort: 9200
        nodes: 9300
        metrics: 9600

      updateStrategy: RollingUpdate
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          memory: 2Gi
      pdb:
        enabled: true
        maxUnavailable: 1
      networkPolicy:
        enabled: false
      env:
        OPENSEARCH_JAVA_OPTS: "-Xms1g -Xmx1g -Dlog4j2.formatMsgNoLookups=true"
        CLUSTER_NAME: "wazuh"
        NETWORK_HOST: "0.0.0.0"
        DISABLE_INSTALL_DEMO_CONFIG: "true" 
      # If defined, storageClassName: <storageClass>
      # If set to "-", storageClassName: "", which disables dynamic provisioning
      # If undefined (the default) or set to null, no storageClassName spec is
      #   set, choosing the default provisioner.
      storageClass: freenas-iscsi-csi
      storageSize: 50Gi

      cred:
        existingSecret: ""
      username: "admin"
      password: "SecretPassword"  


    wazuh:
      env:
        FILEBEAT_SSL_VERIFICATION_MODE: full
      API_USERNAME: "admin"
      API_PASSWORD: "K5j#F2pL8!nW3wUo"        
      service:
        annotations: {}
        ports:
          registration: 1515  # Port for agent registration
          api: 55000          # Wazuh API port
          wazuhInternal: 1516  # Internal communication port, if necessary

      apiCred:
        # 3 Options:
        # 1. Set existing secret name
        # 2. Set username and password manually
        # 3. Let secret be generated automatically (all empty)
        existingSecret: ""
        username: "netadm"
        # The password must have a length between 8 and 64 characters and contain at least one upper and lower case letter, a number, and a symbol(.*+?-).
        password: "K5j#F2pL8!nW3wUo"
      authd:
        existingSecret: ""
        pass: "password"
      master:
        annotations: {}
        podAnnotations: {}

        service:
          type: ClusterIP
          ports:
            registration: 1515   # Agent registration port
            api: 55000           # Wazuh API port
            wazuhInternal: 1516  # Internal Wazuh communication port

        resources:
          limits:
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        
        networkPolicy:
          enabled: false
        
        storageClass: freenas-iscsi-csi
        storageSize: 50Gi

        ingress:
          agentRegistration:
            enabled: false
            ingressClassName: "nginx"
            annotations:
              cert-manager.io/cluster-issuer: ca-certsrv  
            labels: {}
            hosts:
              - host: wazuh-agent.it.excentis.com
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: wazuh-agent-ingress-tls
                hosts:
                  - wazuh-agent.it.excentis.com

        conf: |
          {{- include "wazuh.master.conf" . | indent 2 -}}
        # To be appended to the master.conf
        extraConf: ""
        localInternalOptions: |
          {{- include "wazuh.master.local_internal_options" . | indent 2 -}}

      worker:
        replicas: 2

        annotations: {}
        podAnnotations: {}

        service:
          type: ClusterIP
          annotations: {}
          ports:
            agentEvents: 1514

        resources:
          limits:
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        
        pdb:
          enabled: false
          maxUnavailable: 1
        
        networkPolicy:
          enabled: false

        storageClass: freenas-iscsi-csi
        storageSize: 50Gi

        ingress:
          enabled: true
          ingressClassName: "nginx"
          annotations:
            cert-manager.io/cluster-issuer: ca-certsrv        
          hosts:
            - host: wazuh-worker.it.excentis.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: wazuh-worker-ingress-tls
              hosts:
                - wazuh-worker.it.excentis.com

        conf: |
          {{- include "wazuh.worker.conf" . | indent 2 -}}
        # To be appended to the worker.conf
        extraConf: ""
        localInternalOptions: |
          {{- include "wazuh.worker.local_internal_options" . | indent 2 -}}

```

**Comment by morgoved** [comment]
@71g3pf4c3 could you pls check?

**Comment by envbinsus** [comment]
You can disable network policies and try it out

**Comment by morgoved** [comment]
> [@envbinsus](https://github.com/envbinsus) I did that. No succes. I disabled all network policy's

pls check env - maybe autorization not work beacause you lost spaces.

```
      env:
        FILEBEAT_SSL_VERIFICATION_MODE: full
      API_USERNAME: "admin"
      API_PASSWORD: "K5j#F2pL8!nW3wUo"       
```
