### ISSUE TITLE
Unable to change Wazuh Dashboard password from default "kibanaserver"

### ISSUE THREAD

**Issue by ailoyu** [morgoved/wazuh-helm#19]
## Description
I'm trying to change the default password for the Wazuh Dashboard from "kibanaserver" to a new password, but the dashboard fails to start after the change.

## Steps to reproduce
1. In values.yaml, changed the dashboard credentials:
```yaml
dashboard:
  cred:
    existingSecret: ""
    password: "0l1oZrTvnn83EoX4OXBdvy1p"
    passwordHash: "$2a$12$5SDP7nGBp29vb4ltEYgxJ.E2J1nupIZ/O4AZGsbqPoxdEJIw5xJky" # brypt generated from password 
```

2. Applied the changes using Helm
3. The dashboard pod starts but fails to connect to OpenSearch with errors:
{"type":"log","@timestamp":"2025-06-16T14:02:12Z","tags":["error","opensearch","data"],"pid":55,"message":"[ResponseError]: Response Error"}
{"type":"log","@timestamp":"2025-06-16T14:02:12Z","tags":["error","savedobjects-service"],"pid":55,"message":"Unable to retrieve version information from OpenSearch nodes."}

## Expected behavior
The dashboard should start successfully with the new password.

## Current behavior
The dashboard pod starts but fails to connect to OpenSearch nodes.

## Environment
- Wazuh version: 4.12.0

## Questions
1. What is the correct way to change the Wazuh Dashboard password?
2. Is there a specific format or requirements for the password?
3. Do we need to update any other configurations when changing the dashboard password?

## Additional context
- All OpenSearch indexer nodes are running (3/3 pods)
- The dashboard pod is in Running state but fails to connect to OpenSearch
